### ISSUE TITLE
Results are skewed/bias.

### ISSUE THREAD

**Issue by FirstGearGames** [StinkySteak/unity-netcode-benchmark#2]
First I want to thank you for taking the time to create these tests, and also make it clear this is not an attempt to make my framework specifically look better. There are however some glaring issues that need to be considered when displaying results and deciding how the benchmarks are setup.

1) It's my understanding you did not turn on compression for Netick. If you are running strictly a bandwidth test it would make sense to turn on compression, even if it's not on out of the box.

2) The Mirror test did not work out of the box. To enable a successful Mirror test the setup had to be reworked against Mirror's out of the box recommendations. Also worth noting that to make the test work for Mirror their framework might actually be using more bandwidth than usual due to the necessary modification.

3) FishNet has network level of detail which specifically targets bandwidth usage but you do not have it enabled because it's not on by default. Network Level of Detail is a paid feature, but Fusion is paid so I assume there would be no issue there.

To be absolutely 'out of the box' you would probably have to exclude Mirror stating test could not be completed due to a Mirror bug.
If you are feeling adventurous have other results, perhaps a different branch and new results page, showing tests after optimizations are enabled. These optimizations should only exist on a configuration setup, and not allow modification of the solutions source code.

**Comment by StinkySteak** [comment]
I Heard from Mirror Devs, the bug is intentional (?)
- The NT Target only works on parent somehow
- We have to Instantiate a Player prefab object first to actually 100% on the game state

Others, back to this point
## Why Don’t you enable <insert feature name>?

- This will endlessly happens, because some netcode doesn’t have the feature equivalent
- The time I enable <insert feature name>, other netcode bias will also tell me to "enable this...",  "do this..."
- Example Case
    - I enable compression in Netcode X
    - Another bias netcode tell to enable this too on Netcode Y
    - I enabled that feature on Netcode Y
    - Another bias netcode tell to enable another one on Netcode Z
    - Endless…

But This has the solution, which is to re-benchmark the "optimized" settings & I will include to "Custom User Benchmark"

**Comment by FirstGearGames** [comment]
On mobile so excuse typos.
1. It's definitely a bug in the Mirror code. The player object was spawned
and the parent was set as the target; wasn't root the only object on the
prefabs to begin with?

2. I'm not sure I understand. Are you saying because netcode offer better
enhancements built in, those enhancements should not be included?

**Comment by James-Frowen** [comment]
> 2. I'm not sure I understand. Are you saying because netcode offer better enhancements built in, those enhancements should not be included?

The default settings are what most people will use, especially people who are new to networking and dont know which library to pick.

**Comment by FirstGearGames** [comment]
I don't believe the default settings should be the determining factor, especially since I could just turn LOD on by default and tell people to turn it off if it's not what they need.

But that did make me realize rather than default settings what is more important is what will work for all game types.

My network LOD would be extremely beneficial in casual games but not practical in fast paced competitive games. Because of this I agree now it should be left out of the benchmarks.
