### ISSUE TITLE
Reactor integration

### ISSUE THREAD

**Issue by justinmcmichael** [StinkySteak/unity-netcode-benchmark#5]
Hello, 

My team has a solution called Reactor. We would like to implement our version of the benchmark. The solution we have is a bit different because the server is not Unity-based. May we create a branch to see how we can incorporate your benchmark?

**Comment by StinkySteak** [comment]
I'd suggest to fork it by your own. if your solution is not unity based, then it's not really a great benchmark comparison.
All of the netcodes I did in here is made for Unity

**Comment by justinmcmichael** [comment]
Our solution doesn't use Unity as the server, much like how Photon / Fusion don't use Unity as a room server directly. We do use Unity as the client and the system is scripted within the Unity Editor. 

I have implemented the Move Wandering benchmark. The Reactor API and Unity API are similar enough that the port is straightforward. We could look at implementing functions that abstracts the Unity API so that we can write identical code for the purpose of the benchmark algorithms. This would expand the utility of the benchmark to include more solutions.

**Comment by StinkySteak** [comment]
Thanks, good to know if it works for you.
